source 'https://rubygems.org'
ruby '2.2.0'
gem 'sinatra', '~> 1.4'
gem 'haml', '~> 4.0'
gem 'json', '~> 1.8'
gem 'thin', '~> 1.6'
gem 'chartkick', '~> 1.3'
gem 'rest-client', '~> 1.6'
gem 'sinatra-r18n', '~> 2.0'